---
title: "Caleb Mason"
sortby: "4"
subtitle: "Undergraduate Research Technician"
image: Mason.HEIC
started: "Summer 2025"
toc: false
about:
  id: person-profile
  template: jolla
---

::: {#person-profile}
:::

## About me

I'm an undergraduate student at the University of Tennessee working as a research technician on the Response to Restoration Cub Creek Project with graduate student Lexie Scott. I'm originally from Sevierville, TN, which gave me a strong connection to the Smokies and sparked my interest in fisheries and conservation work. In this role, I've also had the chance to assist with other projects both in the lab and out in the field. I'm an active member of UTK's Student Chapter of The Wildlife and Fisheries Society. Previously, I worked as a Fisheries Intern with the Great Smoky Mountains National Park, where I focused on monitoring freshwater stream species, including the Southern Appalachian Brook Trout. 

## Interests

-   Habitat Biodiversity

-   Conservation of Endangered Species

-   Avian-Aquatic Species Interaction

-   Public Environmental Education
