project:
  type: website
  output-dir: docs

execute:
    freeze: auto
language:
  search-box-placeholder: Search
website:
  search:
    location: navbar
    type: textbox
  title: "UTK Fisheries Research Group"
  navbar:
    logo: img/logo.png
    tools:
      - icon: github
        menu:
          - text: Dr. Molina
            href: https://github.com/moctezumaii
            target: _blank
      - icon: twitter
        menu:
          - text: Dr. Molina
            href: https://x.com/MolinaMoc
            target: _blank
          - text: Dr. Izzo
            href: https://x.com/LisaKIzzo
            target: _blank
      - icon: instagram
        href: https://instagram.com/utk_aquaticslab
        target: _blank
    left:
      - text: "People"
        menu:
          - faculty.qmd
          - students.qmd
      - research.qmd
      - text: "Teaching"
        menu:
          - text: "SNR 610"
            href: htpps://SNR610.com
            target: _blank
          - text: "ANSC/PLSC 571"
            href: htpps://SNR571.com
            target: _blank
      - subunit.qmd
      - opportunities.qmd
  page-footer: "UTK Fisheries Research Group, School of Natural Resources, University of Tennessee"


format:
  html:
    theme:
      - united
      - custom.scss
    css: styles.css
    toc: true
    toc-title: Explore

editor: visual

