---
title: "Opportunities"
---

## Graduate Assistantship

### *Evaluating success in aquatic connectivity restorations* 

**Dr. Augustin Engman and Dr. Lisa Izzo**

We are accepting applications for a M.S. or PhD graduate student research assistant that would develop a thesis or dissertation evaluating aquatic animal movements and the effectiveness of restorations of connectivity in stream ecosystems.

::: callout-important
Review of applications will begin on March 25^th^, 2026 and new applications will not be accepted after April 7^th^, 2026.
:::

#### Duties

In addition to classes and other requirements of the M.S. in Wildlife and Fisheries Science or the PhD in Natural resources program, the student will complete teaching assistant duties, lead their own comprehensive research project, and assist on other research projects. The objectives of the project that the student will address some or all of the following:

1.   Characterizing changes in stream animal assemblages, habitat, and the spatial distribution of animals in response to connectivity restorations, including dam removals and aquatic organism passage (AOP) measures at dams and road-stream crossings
2.  Measuring the dispersal capacity of select stream animals
3.  Investigating the role of physical habitat characteristics, species life history, movement capacity, and the location and magnitude of potential source populations on the likelihood that species will recolonize an area in response to aquatic connectivity restoration

This assistantship will involve extensive and intensive field work, to be conducted in Tennessee and other locations where aquatic connectivity restorations have recently been completed or are ongoing/planned. Field research activities will involve sampling mobile stream organisms (primarily fishes) with multiple gears (i.e., backpack and/or boat electrofishing, seine, snorkeling, various traps etc.), implantation of passive integrated transponder (PIT) tags and marking with visual implant elastomer (VIE), operation of PIT tag arrays and/or portable antennas and may involve extensive travel and overnight stays at/near the field site locations. Lab and office duties will include data and literature reviews, equipment maintenance and construction, statistical analysis, and writing peer-reviewed publications and technical reports.

::: callout-note
## Qualifications

Successful master’s degree applicants will have a B.S. degree in Biology, Ecology, Fisheries and Wildlife Science, or a closely related field, and PhD applicants are expected to hold an M.S. in one of the fields listed above. Applicants must meet all other qualifications for admission to the UTK School of Natural Resources [Master's](https://naturalresources.tennessee.edu/masters-program/) or [PhD program](https://naturalresources.tennessee.edu/doctoral-program/). Applicants must have a strong desire to work in the field and laboratory and are expected to publish their research findings in peer-reviewed journals and present at professional conferences. Previous experience in aquatic field research, use of PIT tags and VIE marking techniques, data analysis using statistical software, and data management skills are preferred. The student must also possess a valid driver's license. Successful candidates will also have demonstrated the ability to manage multiple competing tasks for their time (e.g., writing, data collection, coursework), excellent abilities to work in a team setting, are goal oriented and self-directed.
:::

::: callout-note
## Funding and timeline

Guaranteed financial support is available for 2 years for a Master’s student or 3 years for a PhD student, beginning in August of 2026. Financial support includes a stipend, tuition, and insurance
:::

::: callout-note
## To apply

Please submit the following to Dr. Augustin Engman (aengman\@utk.edu) and Dr. Lisa Izzo (lizzo1\@utk.edu):

1\) Personal statement of research interests and career goals

2\) Resume or curriculum vitae

3\) Transcripts (unofficial is OK)

4\) Contact information for three references
:::

## Volunteer Sign-Up Form

If you are interested in the projects our lab is working on and want to gain some hands on experience, fill out this form! There are seasonal projects that will provide great learning opportunities and we would love to have you out with us! We encourage all UT students to fill out the form who would be interested to volunteer with us for a day of sampling!

[You need to sign in with your UTK Google Account when signing up]{.mark}

[Volunteer Sign Up Form](https://docs.google.com/forms/d/1YLUMSWGRt8R1QC52l4-2wjR_lVdnfVq8xzzBreAFO7Q/edit)

**Deadline**: Open all year